thread/django-lightweight-queue

django_lightweight_queue/worker.py
Rather than poking Redis every second, we can now `BLPOP` every 5 minutes. This has no effect on queue capacity or latency, but means much Redis spam from idle workers.
=> Use a much longer timeout on popping queue jobs

django_lightweight_queue/worker.py
This will reduce the memory usage, by restarting idle workers after 30 minutes.
=> Restart idle workers

django_lightweight_queue/cron_scheduler.py
From django 1.7, INSTALLED_APPS could contain application configuration
classes, this change supports doing that.
=> Use the app registry rather than INSTALLED_APPS directly

django_lightweight_queue/job.py
When DLQ runs middleware pre-job-run, it iterates over the middleware from beginning to end. For correct semantics, when running middleware post-job run, it should iterate in the reverse of that order. 
E.g. consider we have two middlewares running: a transactional middleware and a logging middleware, we want logging to happen before the transaction starts, and after it ends (e.g. so you can log "job finished" once data has actually been written to the database, if you define your middleware as
```
middleware = (
'logging',
'transactional',
)
```
without this change, after a job has run, we would log before committing the transaction.
=> Run the middleware in the correct order

django_lightweight_queue/app_settings.py, django_lightweight_queue/backends/redis.py, django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/backends/synchronous.py, django_lightweight_queue/cron_scheduler.py, django_lightweight_queue/management/commands/queue_configuration.py, django_lightweight_queue/management/commands/queue_runner.py, django_lightweight_queue/runner.py, django_lightweight_queue/task.py, django_lightweight_queue/utils.py, django_lightweight_queue/worker.py
Adds a new queue backend which guarantees (famous last words..) that each job will be run at least once, as opposed to at most once under the `redis` backend. The docstring for ReliableRedisBackend describes how the backend operates, copied here:
```
This backend manages a per-queue-per-worker 'processing' queue. E.g. if we
had a queue called 'django_lightweight_queue:things', and two workers, we
would have:
'django_lightweight_queue:things:processing:1'
'django_lightweight_queue:things:processing:2'
We enqueue tasks to the main queue via LPUSH, and workers grab jobs by
atomically popping jobs from the tail of the main queue into their
processing queue (via BRPOPLPUSH).
On startup we remove all jobs from any processing queues, and move to the
tail of the main queue, i.e. so they're …
```
=> Reliable queue

django_lightweight_queue/management/commands/queue_runner.py, django_lightweight_queue/runner.py
This avoids needing to modify the global configuration when running additional workers.
=> Support specifying the number of workers when specifying a queue to run

django_lightweight_queue/management/commands/queue_configuration.py, django_lightweight_queue/management/commands/queue_runner.py, django_lightweight_queue/runner.py
Tidy up the existing command line options to have slightly cleaner implementations and move to using `BaseCommand` and `argparse` rather than `NoArgsCommand` and `optparse`.
=> Rearrange command line options

django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/job.py, django_lightweight_queue/management/commands/queue_deduplicate.py, runtests, tests/mixins.py, tests/settings.py, tests/test_job.py, tests/test_reliable_redis_backend.py
We ignore the created timestamp as that doesn't actually affect the jobs and is present only for logging purposes.
Note: I've not yet tested the command; I plan to do that tomorrow if I have time.
=> Add a mechanism to deduplicate queues

django_lightweight_queue/runner.py
This prevents an `AttributeError: 'NoneType' object has no attribute 'sigkill_on_stop'` during shutdown if the queue hasn't started fully when it's told to shut down.
=> Avoid error when shutting down part-way through startup

django_lightweight_queue/runner.py
Only run startup for each queue once on each machine
Previously we ran startup on the queue for each worker, which potentially meant running startup for the same queue several times if there were several queue workers for a given queue on a given machine.
=> Reduce startup duplication

django_lightweight_queue/worker.py
This mechanism speeds up shutdown time when there are many idle workers.
=> Have idle workers declare themselves as SIGKILL-able

django_lightweight_queue/runner.py
By killing all the killable workers first, before waiting for any others, we should have more queues cleaned up sooner as they can start shutting down in parallel rather than waiting for non-killable tasks to complete before stopping.
=> Kill workers in parallel

django_lightweight_queue/exposition.py
This appears to have been the proper method to be calling, even under Python 2 ('handle_one_request' doesn't even exist under Python 3).
Despite testing locally I've been unable to reproduce the issues we hit when attempting to use this method in the past, so I suspect that enough other things in the system may have change that they're no longer an issue. Hopefully.
=> Call proper request handler

django_lightweight_queue/cron_scheduler.py, django_lightweight_queue/exposition.py, django_lightweight_queue/runner.py, django_lightweight_queue/worker.py
This is in preparation for changing the worker mechanism to spin up subprocesses rather than using multiprocessing. In short, multiprocessing and threads do not mix well, and on now two occasions we have been bitten by libraries starting background threads in the master process.
A prerequisite to switching over to subprocesses is moving away from multiprocessing's IPC mechanisms. This is that PR.
Previously we used IPC to essentially signal three things:
- Signalling from the master to the workers to gracefully shut down,
- Signalling from the workers to the master that they can be SIGKILLed,
- Signalling from the workers to the master requesting a timeout.
The timeout mechanism is replaced here by using `alarm(3)`, which means that the worker processes do not need to involve the master …
=> Communicate between processes using IPC

django_lightweight_queue/cron_scheduler.py, django_lightweight_queue/exposition.py, django_lightweight_queue/management/commands/queue_worker.py, django_lightweight_queue/runner.py, django_lightweight_queue/worker.py
We've experienced multiple times an issue where Django apps or libraries start background threads. Threading and multiprocessing [do not mix][fork-threads]. Realistically rather than enforcing constraints on what can be mixed with DLQ or coming up with a half-setup where we don't initialise any app configs on the master process, it would be better to run the worker processes as subprocesses with the separation of a call to `execve(2)` in the interim.
This is not a total win–we do lose the benefit of copy-on-write and pay for a greater initialisation time. On the other hand, this provides better separation and makes no assumptions about threads.
There is also a side-benefit of being able to run an individual worker in the foreground.
Since there's now no prohibition on doing so this also …
=> Run workers in subprocesses rather than multiprocessing

README.md, django_lightweight_queue/backends/debug_web.py, django_lightweight_queue/urls.py, django_lightweight_queue/views.py
This is useful for developing and debugging them as well as (if you have Django Debug Toolbar installed) optimising their database queries.
=> Add a view for running jobs in a rolled-back transaction

django_lightweight_queue/runner.py
It's possible that we might want to run the cron but have already configured it. Previously that would error.
=> Re-fetch cron config to avoid possible unbound local

.circleci/config.yml
Based on the `linting` branch (#35) to avoid conflicts, though otherwise unrelated.
This converts the Circle CI build config to use matrix builds and then introduces testing on more recent Python versions.
=> Test on more python versions

django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/logger.py, django_lightweight_queue/management/commands/queue_deduplicate.py, django_lightweight_queue/progress_logger.py, poetry.lock, pyproject.toml
This introduces a simple logger interface so that callers can optionally pass in a message handler and a progress meter.
Supporting the progress meter is the goal here and that is also the reason we cannot simply use the default Python logging support.
Fixes https://github.com/thread/django-lightweight-queue/issues/40
=> Add progress output when deduplicating jobs

.circleci/config.yml, poetry.lock, pyproject.toml
Follow up to https://github.com/thread/django-lightweight-queue/pull/36:
- Relax allowed versions in package dependencies so we can use the package on Django >= 3
- ~~Drop Django 1~~ that would require a major version bump so retracted, we should do it at some point though
- Add Django versions to CI matrix
Have not added more tests although a quick coverage run shows that we're ~50% so there is a chance some of the code breaks on Django >= 3. We're not using this on Django >= 3 at Thread for now so risk there is limited. We can cover these cases once we do (or once I find them through the project I want this for).
=> More Django versions

django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/machine_types.py, django_lightweight_queue/utils.py, tests/test_reliable_redis_backend.py
This aims to speed up queue startup when using this backend as we have seen in production that this can take a while.
In particular if a master process is restarted while other machines are still processing jobs then the startup on that machine can end up retrying the move of in-flight jobs repeatedly while racing against the valid processing by workers elsewhere.
This change limits the scope for this by inspecting the list of processing queues and comparing it to the list of expected queues in order to only rescue jobs from workers which no longer exist.
=> Avoid redundant work in ReliableRedisBackend.startup

django_lightweight_queue/backends/base.py, django_lightweight_queue/backends/redis.py, django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/task.py, tests/test_task.py
This aims to allow clients a more efficient mechanism than just looping over the tasks they're going to enqueue.
For the moment queue overrides are only allowed at a whole batch level, though I think there might be ways we could allow it on a per-job basis. That would involve doing some regrouping of the batching however and is unlikely to be easily efficient. For now therefore we push this up to the caller.
=> Add support for bulk enqueueing tasks

django_lightweight_queue/backends/base.py, django_lightweight_queue/backends/redis.py, django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/management/commands/queue_pause.py, django_lightweight_queue/management/commands/queue_resume.py, django_lightweight_queue/utils.py, poetry.lock, pyproject.toml, tests/settings.py, tests/test_pause_resume.py, tests/test_reliable_redis_backend.py
This can be specified either as a duration or a time to un-pause, though either way the internal implementation relies on Redis' `SETEX` command. Both Redis backends are supported and use the same approach for compatibility.
=> Add a mechanism to pause work on (redis) queues

django_lightweight_queue/cron_scheduler.py
As far as I can tell this is functionally equivalent to the previous approach, however uses a mixture of supported Python and Django import utils rather than relying on `__import__` (which is discouraged) and the deprecated `imp` module.
This resolves deprecation warnings as well as some resource warnings that originated from the previous `imp.find_module` call.
I've manually checked that
- the results of `queue_configurations` don't change (using our main codebase as the test case)
- that errors in the imported modules are similar (the stack trace changes slightly, gaining some `importlib` related layers)
=> Modernise cron configuration import mechanics

django_lightweight_queue/__init__.py
It's deprecated from 3.2 onwards and planned for removal in 4.1.
=> Don't export default_app_config above Django 3.2

django_lightweight_queue/urls.py
Expanding from https://github.com/thread/django-lightweight-queue/pull/61
Django 4.0 removes `url` entirely, so this PR replaces `url` with `re_path` which functions similarly.
=> Fix django 4 regression

django_lightweight_queue/cron_scheduler.py, poetry.lock, pyproject.toml, setup.cfg, tests/test_task.py
The recently added `ignore-without-code` error code checks for this and was included in 0.940.
This PR updates to that, enables that check and then applies fixes related to the update. Happily we didn't have an ignores without codes.
=> Update mypy so we can require error codes on type ignores

django_lightweight_queue/utils.py, tests/_demo_extra_config.py, tests/_demo_extra_config_falsey.py, tests/_demo_extra_config_unexpected.py, tests/test_extra_config.py
This replaces the remaining use of the deprecated `imp` module with `importlib` & adds some tests for the extra configuration loading behaviour.
=> Use importlib for loading extra configuration

tests/settings.py, tests/test_debug_web_backend.py, tests/urls.py
In part so that this has some CI coverage to highlight incompatibilities with new versions of Django.
Builds on #64.
=> Add some tests for the debug web backend

django_lightweight_queue/backends/reliable_redis.py
As the usage has grown we've started seeing some impact form `KEYS` being
blocking and holding up the Redis instance. This is made worse by the
fact than on startup many workers will be attempting this at the same
time.
This change moves to using the non blocking `SCAN` instead. The main
concern here is that the collection of keys can change during iteration
however for this use case I think this is fine as the 2 changes we can
expect are:
- A key goes away: this would be another startup routine removing a
worker key after re-enqueuing its job so should be safe.
- A key appearing: this would be a new worker coming online and should
not be impacting the recovery mechanism as it should also be part of
`expected_processing_queue_keys`.
---
Relying on small scope + existing tests here. 
--- …
=> Limit impact of reliable backend startup routine on Redis load

django_lightweight_queue/backends/base.py, django_lightweight_queue/backends/redis.py, django_lightweight_queue/backends/reliable_redis.py, django_lightweight_queue/management/commands/queue_clear.py, tests/test_reliable_redis_backend.py
This is very common when operating DLQ so I'd like to make our lives easier with a simple command.
(First commit could be extracted to master but I'd prefer to avoid direct push on DLQ and it's probably too trivial enough to warrant an individual PR)
=> Add `queue_clear` command

django_lightweight_queue/command_utils.py, django_lightweight_queue/management/commands/queue_configuration.py, django_lightweight_queue/management/commands/queue_runner.py, django_lightweight_queue/management/commands/queue_worker.py, django_lightweight_queue/runner.py
This introduces a base command class which handles the extra settings since they're now in quite a few places, then uses that as part of passing through the extra settings to the worker processes.
Tested manually using an extra settings file containing `import sys; print(sys.argv)` and checking that it gets run for the worker process.
This changes the signature of the `runner` function, however as that's not meant to be a public API I'm not considering it a breaking change.
Fixes https://github.com/thread/django-lightweight-queue/issues/78
=> Pass through `--extra-settings` to worker processes

django_lightweight_queue/app_settings.py, django_lightweight_queue/backends/redis.py, django_lightweight_queue/backends/reliable_redis.py
Database zero is the default that the Python redis client uses, so default to that to avoid breakage. Since DLQ uses `KEYS` it's potentially useful to be able to run it in its own database as that may limit the performance concerns around the `KEYS` command.
=> Support specifying the Redis Database to use on the host

poetry.lock, pyproject.toml
This has always been optional, it seems it was just missed from the formal specification of the extras.
=> Add an extra for setproctitle

.github/workflows/check.yml, .github/workflows/publish.yml
This avoids warnings from GitHub about legacy NodeJS.
=> Update actions/checkout to v4 for latest NodeJS

.github/workflows/check.yml
We've been running with 4.2 for a while and it's been fine. It seems likely that 5.0 will also be fine from having had a quick look at the release notes.
=> Test against Django 4.2 & 5.0
